# azure-pipelines.yml
trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildReactApp
        displayName: Build React app
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 16.x
            displayName: Install Node.js

          - script: |
              npm ci
              npm run build
            displayName: 'npm install, build'

          - task: ArchiveFiles@2
            displayName: Prepare deploy package
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)/dist
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(System.DefaultWorkingDirectory)/Site.zip
              replaceExistingArchive: true
              verbose: true

          - publish: $(System.DefaultWorkingDirectory)/Site.zip
            artifact: deploy-package

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployReactApp
        displayName: Deploy React app to Azure Web App
        environment: production
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: deploy-package

                - task: AzureWebApp@1
                  displayName: Azure App Service Deploy
                  inputs:
                    resourceGroupName: devops-workshop-rg
                    azureSubscription: dwp-arm-connection
                    appName: dkostmii-web-app
                    startUpCommand: npm run start
                    deploymentMethod: auto
                    package: $(Pipeline.Workspace)/deploy-package/Site.zip
